apiVersion: v1
kind: Service
metadata:
  name: wait-list-frontend-service
  labels:
    app: wait-list-frontend
spec:
  type: LoadBalancer
  selector:
    app: wait-list-frontend
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80