apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-app-deployment
  labels:
    app: soat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat-app
  template:
    metadata:
      labels:
        app: soat-app
    spec:
      containers:
      - name: soat-app
        image: soat-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: soat-secrets
              key: app_key
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: postgres-service
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: soat-config
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: soat-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: soat-secrets
              key: db_password
        - name: REDIS_HOST
          value: redis-service