apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: soat-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soat-app-deployment
  minReplicas: 2 # Número mínimo de réplicas
  maxReplicas: 5 # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Aumentar réplicas se o uso de CPU exceder 70%