apiVersion: v1
kind: Secret
metadata:
  name: soat-secrets
type: Opaque
data:
  app_key: YmFzZTY0OlVXcnRzTzlHOFpNZlQ2R3RHbGxLZldVR3dhZVllL0RQRGRtVkV4UVBuemc9
  db_password: cm9vdA==
  POSTGRES_PASSWORD: cm9vdA==