name: 'Post Terraform Plan to PR'
description: 'Recebe o output do Terraform plan e posta como um comentário formatado em um Pull Request.'

inputs:
  plan_output:
    description: 'A string de saída do comando terraform plan.'
    required: true
  github_token:
    description: 'O token do GitHub para autenticar na API.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Post Plan to PR
      uses: actions/github-script@v7
      shell: bash
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const output = `#### Terraform Plan 📖

          <details><summary>Clique para ver os detalhes</summary>

          \`\`\`terraform
          ${{ inputs.plan_output }}
          \`\`\`

          </details>

          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })