name: CI - MAIN API

on:
  push:
    branches:
      - main
    paths:
      - 'services/core-api/**'
      - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'services/core-api/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/core-api

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo_mysql, pcov
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: |
          # Roda os testes e gera o coverage.xml
          php artisan test --coverage-clover coverage.xml
          
          # Extrai a porcentagem usando regex simples no XML
          COVERAGE=$(grep -o '<metrics.*elements="[0-9]*".*coveredelements="[0-9]*"' coverage.xml | awk -F'"' '{ print int($4 / $2 * 100) }')
          
          echo "Coverage detectado: $COVERAGE%"
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          
          # Define a cor baseada na regra de 70%
          if (( $COVERAGE >= 80 )); then
            echo "COLOR=green" >> $GITHUB_ENV
          elif (( $COVERAGE >= 70 )); then
            echo "COLOR=orange" >> $GITHUB_ENV
          else
            echo "COLOR=red" >> $GITHUB_ENV
          fi

      - name: Create Badge for Core API
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5abf2b6924817bb1f9aa61a28b0268eb
          filename: core-api-coverage.json
          label: PHP Coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ env.COLOR }}