name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'lambda_auth_cpf/**'

  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'lambda_auth_cpf/**'

jobs:
  ###################################################
  # Job 1: Descobre quais arquivos foram alterados  #
  ###################################################
  list-changed-files:
    name: 'List Changed Files'
    runs-on: ubuntu-latest
    outputs:
      auth_changed: ${{ steps.changed-auth-files.outputs.any_changed }}
      database_changed: ${{ steps.changed-database-files.outputs.any_changed }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check for changes in auth files
        id: changed-auth-files
        uses: tj-actions/changed-files@v44
        with:
          # O input correto é 'files'
          files: |
            terraform/auth/**
            lambda_auth_cpf/**

      - name: Check for changes in database files
        id: changed-database-files
        uses: tj-actions/changed-files@v44
        with:
          # Usamos a action uma segunda vez para o outro caminho
          files: |
            terraform/database/**

  #########################################
  # Job 2: Infra de Autenticação          #
  #########################################
  deploy-auth-infra:
    name: 'Terraform Deploy Auth Infra'
    needs: list-changed-files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Condição corrigida para usar o output do passo correto
    if: github.event_name == 'push' || needs.list-changed-files.outputs.auth_changed == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/auth
        env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          PLAN_OUTPUT=$(terraform plan -no-color -input=false)
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ./terraform/auth
        env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: 💬 Print Plan Output (Debug)
        if: github.event_name == 'pull_request'
        run: |
          echo "--- Conteúdo do Plan Capturado ---"
          echo "${{ steps.plan.outputs.plan_output }}"
          echo "------------------------------------"


      - name: Post Plan to PR
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/post-terraform-plan
        with:
          plan_output: ${{ steps.plan.outputs.plan_output }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform/auth
        env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

  #########################################
  # Job 3: Infra do Banco de Dados        #
  #########################################
  deploy-database-infra:
    name: 'Terraform Deploy Database Infra'
    needs: [deploy-auth-infra, list-changed-files]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Condição corrigida para usar o output do passo correto
    if: github.event_name == 'push' || needs.list-changed-files.outputs.database_changed == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/database
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          PLAN_OUTPUT=$(terraform plan -no-color -input=false)
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ./terraform/database
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Post Plan to PR
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/post-terraform-plan
        with:
          plan_output: ${{ steps.plan.outputs.plan_output }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform/database
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
