name: Run Laravel Tests

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          cp .env.example .env
          docker compose up -d --build

      - name: Run tests
        run: docker compose exec -T app php artisan test

      - name: Shutdown containers
        if: always()
        run: docker compose down